Introduction
------------

This is Employee Handbook for RST Python Developers. Document describe how we do our projects.

Status
------------
This is a work in progress. Actually, what you are reading now is a very early draft.


Table of Content
------------


.. toctree::
   :maxdepth: 2

   intro
   principles
   style
   code-review
   refactor
   design-architecture
   modeling
   python
   python-libraries
   testing
   devops
   open-source
   agile
   documentation
   tools
   resources
