Introduction
------------

This is Employee Handbook for our current and future developers.

Status
------------
This is a work in progress. Actually, what you are reading now is a very early draft.

About RST Software House
------------
We are software house from Wroclaw we build online systems & we love to help startups. We create user-friendly web & mobile applications using best programming practices.


tldr
----------

- Be Agile.

  All good practices come from Agile manifesto. be familiar with this. Read more in Agile chapter.

- Write code for others (including "future you"). Check Code Style chapter.

- Practice Test-Driven Development (TDD).

  1. TDD (practiced correctly) helps come with better software design.
  2. It give us confidence that our product work properly, and that we can refactor them without fear of breaking things beyond repair.

  Read more in testing chapter.

- Create Ubiquitous Language for project.

  All project members should be familiar with business logic nomenclature.

- Practice "Documentation Driven Development".
  See documentation chapter in this document.

  Write documentation alongside the code. The simple act of trying to explain to others what we are trying to achieve with our software, and how, helps us clarify our thinking. If it's too hard to explain, then it's probably badly architected, designed or implemented.

- Practice Domain Driven Design (DDD).

  See the Architecture chapter in this document.

- Use on click test and deploy.

  We use docker for CI and deployment configuration. Read DevOps chapter for more information



Table of Content
------------


.. toctree::
   :maxdepth: 2

   intro
   principles
   style
   code-review
   design-architecture
   open-source
   agile
   python-libraries
   resources
   documentation
   refactor
   modeling
   testing
   devops


